package wsr.query.security;

public class CsUsuarioQuery {
	public static final String USUARIO_APP = "SELECT * FROM CS_USUARIO" + 
			" WHERE USERNAME" + 
			" IN(SELECT DISTINCT UG.USUARIO" + 
			" FROM CS_USUARIO_GRUPO UG, CS_GRUPO_SERVICO_APP GSA" +
			" WHERE UG.ID_GRUPO = GSA.ID_GRUPO)"; 
	
	public static final String HQL_USUARIO_APP = "SELECT distinct model " +
			" FROM CsUsuario model" + 
			" INNER JOIN model.grupos g" +
			" INNER JOIN g.servicosApp s";
	
	public static final String USUARIO = "SELECT USERNAME, PASSWORD, CASE WHEN ENABLE = 'T' THEN 1 ELSE 0 END FROM CS_USUARIO WHERE USERNAME = ?"; 
	
	public static final String USUARIO_AUTHORITIES = "SELECT CS_USUARIO.USERNAME, CS_SERVICO_APP.REGRA AS ROLE"+
			" FROM CS_USUARIO, CS_USUARIO_GRUPO, CS_GRUPO_SERVICO_APP, CS_SERVICO_APP" +
			" WHERE CS_USUARIO.USERNAME = CS_USUARIO_GRUPO.USUARIO" +
			" AND CS_USUARIO_GRUPO.ID_GRUPO = CS_GRUPO_SERVICO_APP.ID_GRUPO" +
			" AND CS_GRUPO_SERVICO_APP.ID_SERVICO = CS_SERVICO_APP.ID" +
			" AND CS_USUARIO.USERNAME = ?";
}